Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inmobiliaria.urls')),
]

inmobiliaria/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index , name='index'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('update_account/', views.update_account, name='update_account'),
    path('profile/', views.profile, name='perfil'),
    path('add_property/', views.add_property, name='add_property'),
    path('get_comunas/<int:region_id>/', views.get_comunas, name='get_comunas'),
    path('property/edit/<int:property_id>/', views.edit_property, name='edit_property'),
    path('property/delete/<int:property_id>/', views.delete_property, name='delete_property'),
    path('start_lease/<int:property_id>/', views.start_lease, name='start_lease'),
    path('end_lease/<int:property_id>/', views.end_lease, name='end_lease'),

]

inmobiliaria/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

class UserType(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name

class User(AbstractUser):
    rut = models.CharField(unique=True, max_length=9, validators=[RegexValidator(r'^\d{7,8}[\dK]$')])
    address = models.CharField(max_length=100, blank=False)
    phone = models.CharField(max_length=12)
    user_type = models.ForeignKey(UserType,  on_delete=models.SET_NULL, null=True, blank=True)

    def is_landlord(self):
        return self.user_type and self.user_type.name == 'Arrendador'

    def is_tenant(self):
        return self.user_type and self.user_type.name == 'Arrendatario'

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

class Region(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Comuna(models.Model):
    name = models.CharField(max_length=100)
    region = models.ForeignKey(Region, related_name='comunas', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

class Property(models.Model):
    PROPERTY_TYPE_CHOICES = [
        ('casa', 'Casa'),
        ('departamento', 'Departamento'),
        ('parcela', 'Parcela'),
    ]

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    total_area = models.PositiveIntegerField(blank=False)
    built_area = models.PositiveIntegerField(blank=False)
    parking = models.PositiveSmallIntegerField(default=0)
    rooms = models.PositiveSmallIntegerField(default=0)
    bathrooms = models.PositiveSmallIntegerField(default=0)
    address = models.CharField(max_length=100, blank=False)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, blank=False, null=False)
    commune = models.ForeignKey(Comuna, on_delete=models.CASCADE, blank=False, null=False)
    prop_type = models.CharField(max_length=20, choices=PROPERTY_TYPE_CHOICES, default='departamento')
    price = models.PositiveIntegerField(blank=False)
    owner = models.ForeignKey(User, related_name='owned_properties', on_delete=models.SET_NULL, blank=True, null=True)
    renter = models.ForeignKey(User, related_name='rented_properties', on_delete=models.SET_NULL, blank=True, null=True)
    image = models.URLField(max_length=100,blank=True)
    lease_start_date = models.DateField(null=True, blank=True)
    lease_end_date = models.DateField(null=True, blank=True)
    def __str__(self):
        return f'{self.name} ({self.prop_type}) - Dueño: {self.owner.username if self.owner else "None"}'

inmobiliaria/forms.py
from django import forms
from .models import User, UserType, Property, Comuna
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class UserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'rut', 'address', 'phone']

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['image','name', 'description', 'price', 'prop_type', 'rooms', 'bathrooms', 'parking', 'address','region', 'commune', 'built_area', 'total_area']
        labels = {
            'image': 'Imagen',
            'name': 'Nombre',
            'description': 'Descripción',
            'prop_type': 'Tipo de Propiedad',
            'price': 'Precio',
            'rooms': 'Habitaciones',
            'bathrooms': 'Baños',
            'parking': 'Estacionamiento',
            'address': 'Dirección',
            'region': 'Región',
            'commune': 'Comuna',
            'built_area': 'Superficie construida (m²)',
            'total_area': 'Superficie total (m²)',
            
            
        }
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }
    
    def __init__(self, *args, **kwargs):
        super(PropertyForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        required=True, 
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        error_messages={
            'required': 'El correo electrónico es obligatorio',
            'invalid': 'Introduce una dirección de correo electrónico válida',
        }
    )
    rut = forms.CharField(
        required=True,
        max_length=9,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        error_messages={
            'required': 'El RUT es obligatorio',
            'invalid': 'Introduce un RUT válido',
        }
    )
    address = forms.CharField(
        required=True,
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        error_messages={
            'required': 'La dirección es obligatoria',
        }
    )
    phone = forms.CharField(
        required=True,
        max_length=12,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        error_messages={
            'required': 'El teléfono es obligatorio',
        }
    )

    user_type = forms.ModelChoiceField(
        queryset=UserType.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'}),
        error_messages={
            'required': 'El tipo de usuario es obligatorio',
        }
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'rut', 'address', 'phone', 'user_type')
        labels =  {
            'username': 'Nombre de Usuario',
            'email': 'Email',
            'password1': 'Contraseña',
            'password2': 'Repita Contraseña',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'rut': 'RUT',
            'address': 'Dirección',
            'phone': 'Teléfono',
            'user_type': 'Tipo de Usuario',
        }
        error_messages = {
            'username': {
                'required': 'El nombre de usuario es obligatorio',
                'unique': 'Este nombre de usuario ya está en uso',
            },
            'password1': {
                'required': 'La contraseña es obligatoria',
            },
            'password2': {
                'required': 'Repite la contraseña',
                'password_mismatch': 'Las contraseñas no coinciden',
            },
        }

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].label = 'Nombre de Usuario'
        self.fields['email'].label = 'Email'
        self.fields['password1'].label = 'Contraseña'
        self.fields['password2'].label = 'Repita Contraseña'
        self.fields['first_name'].label = 'Nombre'
        self.fields['last_name'].label = 'Apellidos'
        self.fields['rut'].label = 'RUT'
        self.fields['address'].label = 'Dirección'
        self.fields['phone'].label = 'Teléfono'
        self.fields['user_type'].label = 'Tipo de Usuario'

inmobiliaria/templates/add_property.html
{% extends 'base.html' %}
{% block title %}Inmobiliaria - Agregar Propiedad{% endblock %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="text-center mt-2 mb-5">Agregar Nueva Propiedad</h2>
                    <form method="post" class="mx-auto" style="max-width: 400px;">
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>Por favor corrige los siguientes errores:</strong>
                                <ul>
                                    {% for field in form %}
                                    {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                    {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                        {% for field in form %}
                        <div class="mb-3 row">
                            <label for="{{ field.id_for_label }}" class="col-sm-5 col-form-label">{{ field.label }}</label>
                            <div class="col-sm-7">
                                {% if field.name == "region" %}
                                    <select id="region" name="region" class="form-control">
                                        <option value="">Seleccione una región</option>
                                        {% for region in regions %}
                                        <option value="{{ region.id }}">{{ region.name }}</option>
                                        {% endfor %}
                                    </select>
                                {% elif field.name == "commune" %}
                                    <select id="commune" name="commune" class="form-control">
                                        <option value="">Seleccione una comuna</option>
                                        {% for comuna in comunas %}
                                        <option value="{{ comuna.id }}" {% if selected_commune == comuna.id %}selected{% endif %}>{{ comuna.name }}</option>
                                        {% endfor %}
                                    </select>       
                                {% else %}
                                    {{ field }}
                                {% endif %}
                                {% if field.errors %}
                                <div class="text-danger">
                                    {{ field.errors }}
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-success w-100 my-5">Agregar Propiedad</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inmobiliaria/templates/album.html
<div class="album py-5">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for prop in properties %}
            <div class="col">
                <div class="card shadow-sm h-100">
                    <img src="{{ prop.image }}" class="card-img-top" alt="{{ prop.name }}">
                    <div class="card-body">
                        <h5 class="card-title fs-4">{{ prop.name }}</h5>
                        <p class="card-text text-muted">{{ prop.description }}</p>
                        <ul class="list-group list-group-flush">
                          <li class="list-group-item"><i class="fa-solid fa-bed"></i> {{ prop.rooms }} habitaciones</li>
                          <li class="list-group-item"><i class="fa-solid fa-toilet"></i> {{ prop.bathrooms }} baños</li>
                          <li class="list-group-item"><i class="fa-solid fa-car-side"></i> {{ prop.parking }} estacionamientos</li>
                          <li class="list-group-item"><i class="fa-solid fa-map-location-dot"></i> {{ prop.address }}</li>
                          <li class="list-group-item"><i class="fa-solid fa-location-dot"></i> {{ prop.commune }}, Región de {{ prop.region }}</li>
                          <li class="list-group-item"><i class="fa-solid fa-ruler-combined"></i> {{ prop.built_area }} m² construidos</li>
                          <li class="list-group-item"><i class="fa-solid fa-expand-arrows-alt"></i> {{ prop.total_area }} m² totales</li>
                        </ul>
                        <div class="d-flex justify-content-between align-items-center mt-3">
                            {% if prop.owner == user %}
                            <div class="btn-group bg-light">
                                <a href="{% url 'edit_property' prop.id %}" class="btn btn-sm btn-outline-secondary">Editar</a>
                                {% if prop.renter != null %}
                                    <a href="{% url 'end_lease' prop.id %}" class="btn btn-sm btn-outline-warning">Terminar arriendo</a>
                                {% endif %}
                                <button type="button" class="btn btn-sm btn-outline-danger" onclick="confirmDelete({{ prop.id }})">Eliminar</button>
                            </div>
                            {% elif user.is_tenant and prop.renter == None %}
                            <div class="btn-group">
                                <a href="{% url 'start_lease' prop.id %}" class="btn btn-sm btn-outline-success">Arrendar</a>
                            </div>
                            {% elif user.is_tenant and prop.renter == user %}
                            <div class="btn-group">
                                <a href="{% url 'end_lease' prop.id %}" class="btn btn-sm btn-outline-warning">Terminar arriendo</a>
                            </div>
                            {% endif %}
                            <small class="text-body-secondary text-end">${{ prop.price }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
  </div>
  

inmobiliaria/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?v=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/73f63e3c57.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body>
    <header>
        <div class="container text-center"><img src="{% static 'img/logo.png' %}" alt="logo inmobiliaria" class ="img-fluid"></div>
    </header>
    {% include "./navbar.html" %}
    {% if messages %}
    <div class="container my-3">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert" id="auto-hide-message">
                    {{ message|safe }}
                </div>
            {% else %}
                <div class="alert alert-success" role="alert" id="auto-hide-message">
                    {{ message|safe }}
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    {% block content %}
    {% endblock %}    
    <footer>
        <div class="container my-5 text-center">Creado por Alejandro Olmedo para Desafio Latam - 2024</div>
        <div class="container my-3 text-center">Logotipo hecho con <a href="https://www.designevo.com/es/" title="Creador de logotipos gratis online">DesignEvo</a></div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

inmobiliaria/templates/edit_property.html
{% extends 'base.html' %}
{% block title %}Editar Propiedad{% endblock %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="text-center mt-2 mb-5">Editar Propiedad</h2>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="mb-3 row">
                            <label for="{{ field.id_for_label }}" class="col-sm-5 col-form-label">{{ field.label }}</label>
                            <div class="col-sm-7">
                                {{ field }}
                                {% if field.errors %}
                                <div class="text-danger">
                                    {{ field.errors }}
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-success w-100 my-5">Guardar Cambios</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inmobiliaria/templates/index.html
{% extends "./base.html" %}
{% block title %}Inmobiliaria{% endblock %}
{% block content %}
    <div class="container my-5">
        <form method="get" class="row g-3 mb-5">
            <div class="col-md-4">
                <label for="prop_type" class="form-label">Tipo de Propiedad</label>
                <select id="prop_type" name="prop_type" class="form-select">
                    <option value="">Todos</option>
                    <option value="casa" {% if selected_type == "casa" %}selected{% endif %}>Casa</option>
                    <option value="departamento" {% if selected_type == "departamento" %}selected{% endif %}>Departamento</option>
                    <option value="parcela" {% if selected_type == "parcela" %}selected{% endif %}>Parcela</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="region" class="form-label">Región</label>
                <select id="region" name="region" class="form-select">
                    <option value="">Todas</option>
                    {% for region in regions %}
                    <option value="{{ region.id }}" {% if selected_region == region.id %}selected{% endif %}>{{ region.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-4">
                <label for="commune" class="form-label">Comuna</label>
                <select id="commune" name="commune" class="form-select">
                    <option value="">Todas</option>
                    {% for comuna in comunas %}
                    <option value="{{ comuna.id }}" {% if selected_commune == comuna.id %}selected{% endif %}>{{ comuna.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-12 text-center">
                <button type="submit" class="btn btn-success">Filtrar</button>
            </div>
        </form>
        {% include "./album.html" %}
    </div>
{% endblock %}

inmobiliaria/templates/login.html
{% extends 'base.html' %}
{% block title %}Inmobiliaria - Login{% endblock %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="text-center">Login</h2>
                    <form method="post" class="mx-auto" style="max-width: 400px;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Usuario</label>
                            <input type="text" name="username" id="id_username" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Password</label>
                            <input type="password" name="password" id="id_password" class="form-control" required>
                        </div>
                        <button type="submit" class="btn btn-success w-100">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inmobiliaria/templates/navbar.html
<nav class="container navbar navbar-dark navbar-expand-lg bg-success sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Bienvenid@{% if user.is_authenticated %}, {{ user.first_name }}{% endif %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
          <a class="nav-link active" aria-current="page" href="/">Inicio</a>
          {% if user.is_authenticated %}
          <a class="nav-link" href="/profile">Tu perfil</a>
          {% endif %}
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a></li>
            <a class="nav-link" href="{% url 'signup' %}">Registrarse</a></li>
      {% endif %}
        </div>
      </div>
    </div>
</nav>

inmobiliaria/templates/profile.html
{% extends "./base.html" %}
{% block title %}Inmobiliaria{% endblock %}
{% block content %}
    <div class="container text-center my-5">
        <button class="btn btn-success" data-bs-toggle="offcanvas" data-bs-target="#editAccountOffcanvas"
            aria-controls="editAccountOffcanvas">
            Editar Cuenta
        </button>
        {% if user.is_landlord %}
        <a href="/add_property">
            <button class="btn btn-success">
                Añadir Propiedad
            </button>
        </a> 
        {% endif %}
    </div>
    {% include './updateacc.html' %}
    {% if user.is_landlord %}
        <h3 class="container text-center my-3">Tus propiedades</h3>
    {% elif user.is_tenant %}
        <h3 class="container text-center my-3">Tus arriendos</h3>
    {% endif %}
    {% include "./album.html" %}
{% endblock %}

inmobiliaria/templates/signup.html
{% extends 'base.html' %}
{% block title %}Inmobiliaria - Registro{% endblock %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="text-center mt-2 mb-5">Registrar nuevo usuario</h2>
                    <form method="post" class="mx-auto" style="max-width: 400px;">
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>Por favor corrige los siguientes errores:</strong>
                                <ul>
                                    {% for field in form %}
                                    {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                    {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                        {% for field in form %}
                        <div class="mb-3 row">
                            <label for="{{ field.id_for_label }}" class="col-sm-5 col-form-label">{{ field.label }}</label>
                            <div class="col-sm-7">
                                {{ field }}
                                {% if field.errors %}
                                <div class="text-danger">
                                    {{ field.errors }}
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100 my-5">Registrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inmobiliaria/templates/updateacc.html
<div class="offcanvas offcanvas-end text-white bg-dark" tabindex="-1" id="editAccountOffcanvas"
    aria-labelledby="editAccountOffcanvasLabel">
    <div class="offcanvas-header">
        <h5 id="editAccountOffcanvasLabel">Editar Datos de la Cuenta</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <form method="post" action="{% url 'update_account' %}">
            {% csrf_token %}
            {{ user_form.non_field_errors }}

            <div class="mb-3">
                <label for="id_username" class="form-label">Nombre de Usuario</label>
                <input type="text" class="form-control" id="id_username" name="username" value="{{ user_form.username.value|default:user.username }}">
            </div>

            <div class="mb-3">
                <label for="id_email" class="form-label">Correo Electrónico</label>
                <input type="email" class="form-control" id="id_email" name="email" value="{{ user_form.email.value|default:user.email }}">
            </div>

            <div class="mb-3">
                <label for="id_first_name" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user_form.first_name.value|default:user.first_name }}">
            </div>

            <div class="mb-3">
                <label for="id_last_name" class="form-label">Apellido</label>
                <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ user_form.last_name.value|default:user.last_name }}">
            </div>

            <div class="mb-3">
                <label for="id_rut" class="form-label">RUT</label>
                <input type="text" class="form-control" id="id_rut" name="rut" value="{{ user_form.rut.value|default:user.rut }}">
            </div>

            <div class="mb-3">
                <label for="id_address" class="form-label">Dirección</label>
                <input type="text" class="form-control" id="id_address" name="address" value="{{ user_form.address.value|default:user.address }}">
            </div>

            <div class="mb-3">
                <label for="id_phone" class="form-label">Teléfono</label>
                <input type="text" class="form-control" id="id_phone" name="phone" value="{{ user_form.phone.value|default:user.phone }}">
            </div>

            {{ password_form.non_field_errors }}
            <div class="mb-3">
                <p class="text-center my-4">Para cambiar tu contraseña, debes ingresar la contraseña actual.</p>
            </div>

            <div class="mb-3">
                <label for="id_old_password" class="form-label">Contraseña Actual (opcional)</label>
                <input type="password" class="form-control" id="id_old_password" name="old_password">
            </div>

            <div class="mb-3">
                <label for="id_new_password1" class="form-label">Nueva Contraseña (opcional)</label>
                <input type="password" class="form-control" id="id_new_password1" name="new_password1">
            </div>

            <div class="mb-3">
                <label for="id_new_password2" class="form-label">Confirmar Nueva Contraseña</label>
                <input type="password" class="form-control" id="id_new_password2" name="new_password2">
            </div>

            <button type="submit" class="btn btn-success">Guardar Cambios</button>
        </form>
    </div>
</div>